# Generate Figure S1: Domain-level abundance comparison plots
# Requires: data/classification/taxonomic_rank_summaries/domain/bracken_domain_estimates.rds
# (Generated by: scripts/summarize_outputs/summarize_domain_pct.r)

library(tidyverse)
library(ggpubr)

domain_output <- readRDS("data/classification/taxonomic_rank_summaries/domain/bracken_domain_estimates.rds")


# Create list of all samples from each database
common_samples <- domain_output %>% distinct(sampleID, db_name) %>% count(sampleID) %>% filter(n > 2) %>% select(sampleID) %>% unlist

options(scipen=999)
fig_s1 = ggplot(domain_output %>% 
           mutate(db_name = recode(db_name, "soil_microbe_db" = "SoilMicrobeDB",
                                               "pluspf" = "PlusPF",
                                               "gtdb_207" = "GTDB r207")) %>% 
           filter(sampleID %in% common_samples) %>% 
           filter(taxon %in% c("Archaea","Bacteria","Eukaryota")),
           aes(x = db_name, y = percentage, color=db_name)) +
    geom_violin(color=1, draw_quantiles = c(.5)) +
    geom_jitter(size=3, alpha=.2) +
    facet_wrap(~taxon, scale="free_y")  +
    theme_minimal(base_size = 20) +
    ylab("Estimated abundances") +
    xlab("Database") +
    theme(axis.text.x=element_text(angle = 310, vjust=1, hjust = 0)) + 
    stat_compare_means(method = "t.test", comparisons = list(c("SoilMicrobeDB","PlusPF"),
                                                          c("SoilMicrobeDB","GTDB r207"),
                                                          c("GTDB r207","PlusPF")), hide.ns = T) + 
    guides(color="none")

# Save figure
ggsave("manuscript_figures/fig_s1.png", fig_s1, width = 14, height = 5, units = "in", dpi = 300)
cat("✅ Saved figure to: manuscript_figures/fig_s1.png\n")


