# Calculate proportion of fungal phylum reads not identified to genus level
# Input: Phylum and genus merged lineage CSV files from soil_microbe_db
# Output: Calculates pct_not_genus = 1 - (genus_fungi / phylum_fungi)
#         Uses Bracken estimates (new_est_reads) which redistribute reads hierarchically
#         Phylum-level Bracken includes genus-level reads redistributed upward
#         So phylum_fungi >= genus_fungi, and the difference represents reads only at phylum level
#         Prints histogram and median of pct_not_genus
#         This metric indicates how much fungal diversity is unclassified at genus level

library(tidyverse)
library(data.table)

fungal_phyla <- c("Ascomycota", "Basidiomycota", "Blastocladiomycota",
                 "Chytridiomycota", "Cryptomycota", "Mucoromycota",
                 "Microsporidia", "Olpidiomycota", "Zoopagomycota")

phylum_file <- "data/classification/taxonomic_rank_summaries/soil_microbe_db_phylum_merged_lineage.csv"
genus_file <- "data/classification/taxonomic_rank_summaries/soil_microbe_db_genus_merged_lineage.csv"

if(!file.exists(phylum_file)) {
    stop("Phylum merged lineage CSV not found: ", phylum_file, 
         "\nThis file is generated by 03_add_lineage.sh in the run_workflow pipeline.")
}
if(!file.exists(genus_file)) {
    stop("Genus merged lineage CSV not found: ", genus_file,
         "\nThis file is generated by 03_add_lineage.sh in the run_workflow pipeline.")
}

lineage_phylum <- fread(phylum_file)
lineage_genus <- fread(genus_file)

lineage_phylum_fungi <- lineage_phylum %>% 
    filter(name %in% fungal_phyla) %>% 
    group_by(sample_id) %>% 
    summarize(phylum_fungi = sum(new_est_reads), .groups = "drop") %>%
    separate(sample_id, into = c("sampleID", "db_name"), sep = "COMP_", remove = FALSE, extra = "merge") %>%
    mutate(sampleID = str_remove(sample_id, paste0("_", db_name))) %>%
    select(sampleID, phylum_fungi)

lineage_genus_fungi <- lineage_genus %>% 
    filter(grepl(paste0(fungal_phyla, collapse = "|"), lineage)) %>%
    group_by(sample_id) %>% 
    summarize(genus_fungi = sum(new_est_reads), .groups = "drop") %>%
    separate(sample_id, into = c("sampleID", "db_name"), sep = "COMP_", remove = FALSE, extra = "merge") %>%
    mutate(sampleID = str_remove(sample_id, paste0("_", db_name))) %>%
    select(sampleID, genus_fungi)

lineage_merged <- merge(lineage_phylum_fungi, lineage_genus_fungi, all = TRUE) %>%
    mutate(
        phylum_fungi = ifelse(is.na(phylum_fungi), 0, phylum_fungi),
        genus_fungi = ifelse(is.na(genus_fungi), 0, genus_fungi),
        pct_not_genus = ifelse(phylum_fungi > 0, 1 - (genus_fungi / phylum_fungi), NA)
    ) %>%
    filter(!is.na(pct_not_genus) & phylum_fungi > 0)

hist(lineage_merged$pct_not_genus)
median(lineage_merged$pct_not_genus)
